#!/bin/bash 
echo "\"(Ôo)'"
#!/bin/bash
cat /etc/passwd
#!/bin/bash 
cat /etc/passwd /etc/hosts
#!/bin/bash 
tail /etc/passwd
#!/bin/bash
head /etc/passwd
#!/bin/bash
head --lines=3 iacta | tail --lines=1
#!/bin/bash
echo 'Best School' > \\\*\\\\\'\"Best\ School\"\\\'\\\\\*\$\\\?\\\*\\\*\\\*\\\*\\\*\:\)
#!/bin/bash
ls -la > ls_cwd_content
#!/bin/bash
tail --lines=1 iacta >> iacta
#!/bin/bash
find . -type f -name '*.js' -delete
#!/bin/bash
find . -type d -path './*' -print | wc -l
#!/bin/bash
ls -t | head
#!/bin/bash
sort | uniq -u
#!/bin/bash
grep -i "root" /etc/passwd
#!/bin/bash
grep -c "bin" /etc/passwd
#!/bin/bash
grep -iA 3 "root" /etc/passwd
#!/bin/bash
grep -v "bin" /etc/passwd
#!/bin/bash
grep ^[A-Za-z] /etc/ssh/sshd_config
#!/bin/bash
tr Ac Ze
#!/bin/bash
tr -d cC
#!/bin/bash
rev
#!/bin/bash
cut -d':' -f1,6 /etc/passwd | sort
#!/bin/bash
find . -empty -printf %f'\n'
#!/bin/bash
find . -type f -name \*.gif -printf "%f\n" | LC_ALL=C sort -f | rev | cut -b 5- | rev
#!/bin/bash
cut -c 1 | paste -s -d ''
